// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvvpaajkqhklqfltiirx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2dnBhYWprcWhrbHFmbHRpaXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTA3MzcsImV4cCI6MjA1OTc4NjczN30.RAYHNwIX42MDguEl46WYXaCTmsc6iPGVY7dKwksDEwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);